##########################################################
# GISTIC Copy Number PDX                                 #
# Filtered out HPV/Lymphoma                              #
#                                                        #
# PN0039A - Basal HNSCC                                  #
#                                                        #
# Mary-Kate Riley 11-08-25                               #
##########################################################

setwd("")

# Clean environment
rm(list = ls(all.names = TRUE)) # will clear all objects including hidden objects
gc() # free up memory and report the memory usage

# Load packages
library(tidyverse)
library(dplyr)
library(clusterProfiler)
#BiocManager::install("maftools")
library(maftools)
#BiocManager::install("BSgenome.Hsapiens.UCSC.hg38")
library(BSgenome.Hsapiens.UCSC.hg38)
#BiocManager::install("NMF")
library(NMF)
library(ComplexHeatmap)
library(pheatmap)
library(gplots)
library(circlize) #colourRamp2()
#library(RColorBrewer)
library(gtools) # orders chromosomes using mixedsort()


########################################################## READ DATA ##########################################################

all.lesions <- "./0_data/GISTIC/PDX_HPVLymp_Rem/all_lesions.conf_99_renamed.txt"
amp.genes <- "./0_data/GISTIC/PDX_HPVLymp_Rem/amp_genes.conf_99.txt"
del.genes <- "./0_data/GISTIC/PDX_HPVLymp_Rem/del_genes.conf_99.txt"
scores.gis <- "./0_data/GISTIC/PDX_HPVLymp_Rem/scores.gistic"

########################################################## SET VARIABLES ##########################################################
data <- "./0_data/PDX/"
pipelines <- "./2_pipelines/GISTIC/PDX/NEW_Filtered_HPV_Lymphoma/"
output <- "./3_output/GISTIC/PDX/NEW_Filtered_HPV_Lymphoma/"
title <- "HN0039A_Filtered_PDX"
plot_title <- "GISTIC PDX: Filtered for HPV and Lymphoma"

########################################################## GISTIC MAFTOOLS ##########################################################
# Summarise output files generated by GISTIC
laml.gistic = readGistic(gisticAllLesionsFile = all.lesions, gisticAmpGenesFile = amp.genes, gisticDelGenesFile = del.genes, gisticScoresFile = scores.gis)
laml.gistic
write.GisticSummary(laml.gistic,paste0(pipelines,"GISTICSummary"))

# Visualise GISTIC results
# Genome plot 
pdf(paste0(output,title,"_GISTIC_genomeplot.pdf"),width = 10, height = 8)
gisticChromPlot(gistic = laml.gistic, markBands = "all", 
                txtSize = 1.2, cytobandTxtSize = 0.6,
                fdrCutOff = 0.05, ref.build = "hg38")
dev.off()

# Bubble plot
png(paste0(output,title,"_GISTIC_bubbleplot.png"),width = 7.5, height = 6, units = "in", res = 200)
gisticBubblePlot(gistic = laml.gistic, markBands = "all")
dev.off()

