##########################################################
# GISTIC Copy Number PDX                                 #
# RESPONDERS + NONRESPONDERS                             #
# Filtered out HPV/Lymphoma                              #
#                                                        #
# PN0039A - Basal HNSCC                                  #
#                                                        #
# Mary-Kate Riley 23-08-2025                             #
##########################################################

setwd("/Users/mary-kateriley/Library/CloudStorage/OneDrive-Queen'sUniversityBelfast/Data Analysis/HNC/Basal PDX/Reanlysis Exome Basal '24")

# Clean environment
rm(list = ls(all.names = TRUE)) # will clear all objects including hidden objects
gc() # free up memory and report the memory usage

# Load packages
library(tidyverse)
library(dplyr)
library(tidyr)
#BiocManager::install("maftools")
library(maftools)
#BiocManager::install("BSgenome.Hsapiens.UCSC.hg38")
library(BSgenome.Hsapiens.UCSC.hg38)
#BiocManager::install("NMF")
library(NMF)
library(ComplexHeatmap)
library(pheatmap)
library(circlize)
library(gplots)
library(clusterProfiler)
library(RColorBrewer)


########################################################## READ DATA ##########################################################

# Read in metadata file
ClinicalInfo <- read.csv("./0_data/PDX/PDX_Rem_HPV_Lymphoma_Clinical_Information.csv", header = T, row.names = 1)
ClinicalInfo <- ClinicalInfo  %>%
  filter(!is.na(Definitive_Response_3_6wk))

ClinicalInfo$Definitive_Response_3_6wk <- factor(ClinicalInfo$Definitive_Response_3_6wk, levels = c("Responder", "NonResponder"))
levels(ClinicalInfo$Definitive_Response_3_6wk)

ClinicalInfo$Response_3_6wk <- factor(ClinicalInfo$Response_3_6wk, levels = c("PR", "SD", "PD", "No_data"))
levels(ClinicalInfo$Response_3_6wk)

# Set rownames in ClinicalInfo to Tumor_Sample_Barcode
head(ClinicalInfo)
rownames(ClinicalInfo)=ClinicalInfo[, ncol(ClinicalInfo)] # Set last column as rownames (Tumor_Sample_Barcode)
head(ClinicalInfo)

# Read in SHH GMT and EGFR ligands Files and KRT genes of interest
SHH <- read.gmt("./0_data/GMT/SHH/BIOCARTA_SHH_PATHWAY.v2023.2.Hs.gmt")
SHH <- SHH$gene 
EGFR <- read.csv("./0_data/GMT/EGFR/EGFR_ligands.csv", header = T)
EGFR <- EGFR$EGF_Ligands
EGFR <- c("EGFR",unique(EGFR) %>% 
            setdiff("EGFR") %>% 
            sort())
EGFR <- c(EGFR, "CAV1", "SOX2")
KRT <- c("KRT8", "KRT18", "KRT5", "KRT14", "KRT1", "KRT10")

reccurant_cna <- c("TP63", "SOX2", "PIK3CA", "CCDN1", "FAT1", "CSMD1", "CDKN2A", "SMAD4", "CCND1")
########################################################## SET VARIABLES ##########################################################
data <- "./0_data/PDX/"
pipelines <- "./2_pipelines/GISTIC/PDX/NEW_Filtered_HPV_Lymphoma/"
output <- "./3_output/GISTIC/PDX/NEW_Filtered_HPV_Lymphoma/"
title <- "HN0039A_Filtered_PDX_RVNR_"
plot_title <- "GISTIC PDX:"

response_colours <- c("blue","red","black")
names(response_colours) <- c("Responder","NonResponder","No_data")
response_colours <- list(Definitive_Response_3_6wk=response_colours)

site_colours <- c("#40e0d0", "darkgreen", "purple", "#FBEC5D", "darkorange", "#E30B5C", "darkgrey")
names(site_colours) <- c("Larynx", "Oropharynx", "Hypopharynx", "Oral Cavity", "Larynx + Oral Cavity", "Oral Cavity + Oropharynx", "Unknown")
site_colours <- list(Site.of.Primary=site_colours)

response_colours_2 <- c("blue","red")
names(response_colours_2) <- c("Responder","NonResponder")
response_colours_2 <- list(Definitive_Response_3_6wk=response_colours_2)

########################################################## GISTIC MAFTOOLS ##########################################################
# Summarise output files generated by GISTIC
all.lesions <- "./0_data/GISTIC/PDX_HPVLymp_Rem/all_lesions.conf_99_renamed.txt"
amp.genes <- "./0_data/GISTIC/PDX_HPVLymp_Rem/amp_genes.conf_99.txt"
del.genes <- "./0_data/GISTIC/PDX_HPVLymp_Rem/del_genes.conf_99.txt"
scores.gis <- "./0_data/GISTIC/PDX_HPVLymp_Rem/scores.gistic"

laml.gistic = readGistic(gisticAllLesionsFile = all.lesions, gisticAmpGenesFile = amp.genes, gisticDelGenesFile = del.genes, gisticScoresFile = scores.gis)
laml.gistic
write.GisticSummary(laml.gistic,paste0(pipelines,"GISTICSummary"))

# Visualise GISTIC results
# Genome plot
pdf(paste0(output,title,"_GISTIC_genomeplot.pdf"),width = 7.5, height = 6)
gisticChromPlot(gistic = laml.gistic, markBands = "all", fdrCutOff = 0.05, ref.build = "hg38")
dev.off()

# Bubble plot
pdf(paste0(output,title,"_GISTIC_bubbleplot.pdf"),width = 7.5, height = 6)
gisticBubblePlot(gistic = laml.gistic, markBands = "all", fdrCutOff = 0.05)
dev.off()

# Set oncoplot colours as red and blue and not red and green
amp_del_cols <- c("red","blue")
names(amp_del_cols) <- c("Amp","Del")

# Oncoplot
pdf(paste0(output,title,"_GISTIC_orderedbyresponse_oncoplot.pdf"),width = 7.5, height = 6)
gisticOncoPlot(gistic = laml.gistic, 
               clinicalData = ClinicalInfo, 
               clinicalFeatures = c('Definitive_Response_3_6wk','Site.of.Primary'), 
               sortByAnnotation = TRUE, 
               fontSize = 0.45,
               annotationColor = c(response_colours,site_colours),
               colors = amp_del_cols)
dev.off()

pdf(paste0(output,title,"_GISTIC_orderedbySite_oncoplot.pdf"),width = 7.5, height = 6)
gisticOncoPlot(gistic = laml.gistic, 
               clinicalData = ClinicalInfo, 
               clinicalFeatures = c('Site.of.Primary','Definitive_Response_3_6wk'), 
               sortByAnnotation = TRUE, 
               annotationColor = c(site_colours,response_colours),
               fontSize = 0.45,
               colors = amp_del_cols)
dev.off()



########################################################## BROAD VALUEWS BY ARM ##########################################################
# log2 PDX vs log2 NMH
gistic_output = read.table("./0_data/GISTIC/PDX_HPVLymp_Rem/broad_values_by_arm.txt", header=T, row.names = 1, sep="\t")
colnames(gistic_output)

# Rename column names so it matches the PDX sample names
colnames(gistic_output) <- substr(colnames(gistic_output), 6, 17)
colnames(gistic_output)

# Only include columns that have samples present in ClinicalInfo
gistic_output <- gistic_output[, colnames(gistic_output) %in% rownames(ClinicalInfo)]
colnames(gistic_output)

gistic_output <- as.matrix(gistic_output)

# Subset annotation data to include only samples present in gistic_output
annotations <- ClinicalInfo[colnames(gistic_output), c("Definitive_Response_3_6wk", "Response_3_6wk", "Sex", "Site.of.Primary")]
annotations <- data.frame(annotations)
annotations$Site.of.Primary[annotations$Site.of.Primary == ""] <- "Unknown"

annotations$Site.of.Primary <- factor(annotations$Site.of.Primary)
annotations$Site.of.Primary
# Set column names of ind to match row names 
colnames(gistic_output) <- rownames(annotations)
identical(rownames(annotations), colnames(gistic_output)) # check if row names match



# Set annotation colours
ann_colors <- list(
  Definitive_Response_3_6wk = c("Responder" = "#1B7837FF", "NonResponder" = "#762A83FF", "No_data" = "#666666FF"),
  Response_3_6wk = c("PR" = "#5AAE61FF", "SD" = "#F7F7F7FF", "PD" = "#762A83FF", "No_data" = "#666666FF"),
  Sex = c("M" = "#A6CEE3", "F" = "#FB9A99"),
  Site.of.Primary = c("Larynx" = "#1B9E77FF", "Oropharynx" = "#66A61EFF", "Hypopharynx" = "#7570B3FF", "Oral Cavity" = "#E6AB02FF", "Larynx + Oral Cavity" = "#D95F02FF", "Oral Cavity + Oropharynx" = "#E7298AFF", "Unknown" = "#666666FF"))


# Count values in 0.1 bins (incl. negatives)
g_vals <- as.numeric(na.omit(as.vector(gistic_output)))
bins <- cut(g_vals, breaks = seq(floor(min(g_vals)), ceiling(max(g_vals)), by = 0.1), right = FALSE)
table(bins)


# Min and max
min_val <- min(gistic_output, na.rm = TRUE) # -1.293
max_val <- max(gistic_output, na.rm = TRUE) # +3.657

# Define the number of color steps for negative and positive sides
n_colors_neg <- 50
n_colors_pos <- 50
total_colors <- n_colors_neg + n_colors_pos # 100

# Create breaks for the negative side (min_val to 0)
breaks_neg <- seq(min_val, 0, length.out = n_colors_neg + 1)

# Create breaks for the positive side (0 to max_val)
breaks_pos <- seq(0, max_val, length.out = n_colors_pos + 1)
# Combine, removing the duplicate 0
heatmap_breaks_asym <- unique(c(breaks_neg, breaks_pos))

# Generate the diverging color palette with the total number of colors
heatmap_colors <- colorRampPalette(rev(brewer.pal(n = 11, name = "RdBu")))(total_colors)

# Responder sits on the right
ann_legend_param <- list(
  Definitive_Response_3_6wk = list(
    at = c("NonResponder","Responder"),
    labels = c("NonResponder","Responder"),
    direction = "horizontal"))

# Asymmetrical breaks centered at zero
pdf(paste0(output, title, "NewBroadValuesByArm_ThesisReady_AsymBreaks.pdf"), width = 10, height = 9)
ComplexHeatmap::pheatmap(
  mat = gistic_output,
  color = heatmap_colors,
  breaks = heatmap_breaks_asym,
  na_col = "grey",
  legend_breaks = c(round(min_val, 1), 0, round(max_val, 1)),
  annotation_col = annotations,
  annotation_colors = ann_colors,
  annotation_names_col = FALSE,
  cluster_cols = TRUE,
  cluster_rows = FALSE,
  show_colnames = FALSE,
  border_color = NA,
  fontsize = 12,
  name = " ",
  main = paste0(plot_title," Broad Values by Arm"),)
dev.off()

pdf(paste0(output, title, "NewBroadValuesByArm_ColumnSplit_ThesisReady_AsymBreaks.pdf"), width = 10, height = 9)
ComplexHeatmap::pheatmap(
  mat = gistic_output,
  color = heatmap_colors,
  breaks = heatmap_breaks_asym,
  na_col = "grey",
  legend_breaks = c(round(min_val, 1), 0, round(max_val, 1)),
  annotation_col = annotations,
  annotation_colors = ann_colors,
  annotation_names_col = FALSE,
  cluster_cols = TRUE,
  cluster_rows = FALSE,
  show_colnames = FALSE,
  column_split = annotations$Definitive_Response_3_6wk,
  border_color = NA,
  fontsize = 12,
  name = " ",
  main = paste0(plot_title," Broad Values by Arm"),)
dev.off()



########################################################## ALL THRESHOLD BY GENES HEATMAP ##########################################################

# Read data
all_tresh_genes <- read.delim("./0_data/GISTIC/PDX_HPVLymp_Rem/all_thresholded.by_genes.txt", header = TRUE, stringsAsFactors = FALSE)

# Make longer
merged_data <- all_tresh_genes %>%
  pivot_longer(cols = starts_with("log2"),
               names_to = "Sample_ID",
               values_to = "CopyNumber")
merged_data$Tumor_Sample_Barcode <- substr(merged_data$Sample_ID, 6, 17)

# Create list with all genes of interest
all_genes_of_interest <- list(SHH, EGFR, KRT, reccurant_cna)
all_genes_of_interest <- unlist(all_genes_of_interest)

# Filter the merged data to only include the genes of interest
long_gene_data <- merged_data %>%
  filter(Gene.Symbol %in% all_genes_of_interest) 
colnames(long_gene_data)

# Make longer so genes are rownames
long_gene_data <- long_gene_data %>% 
  dplyr::select(Tumor_Sample_Barcode, Gene.Symbol, CopyNumber) %>% 
  pivot_wider(names_from = Tumor_Sample_Barcode, values_from = CopyNumber, values_fill = 0) %>% 
  column_to_rownames("Gene.Symbol")

# Subset annotation data to include only samples present in gistic_output
annotations <- ClinicalInfo[colnames(long_gene_data), c("Definitive_Response_3_6wk", "Response_3_6wk", "Sex", "Site.of.Primary")]
annotations <- annotations[!is.na(annotations$Definitive_Response_3_6wk), ]
annotations$Site.of.Primary[annotations$Site.of.Primary == ""] <- "Unknown"

annotations$Site.of.Primary <- factor(annotations$Site.of.Primary)
annotations$Site.of.Primary

# Set column names of long_gene_data to match row names
long_gene_data <- long_gene_data[, rownames(annotations), drop = FALSE]

# Set column names of ind to match row names 
identical(rownames(annotations), colnames(long_gene_data)) # check if row names match

# Set annotation colours
ann_colors <- list(
  Definitive_Response_3_6wk = c("Responder" = "#1B7837FF", "NonResponder" = "#762A83FF", "No_data" = "#666666FF"),
  Response_3_6wk = c("PR" = "#5AAE61FF", "SD" = "#F7F7F7FF", "PD" = "#762A83FF", "No_data" = "#666666FF"),
  Sex = c("M" = "#A6CEE3", "F" = "#FB9A99"),
  Site.of.Primary = c("Larynx" = "#1B9E77FF", "Oropharynx" = "#66A61EFF", "Hypopharynx" = "#7570B3FF", "Oral Cavity" = "#E6AB02FF", "Larynx + Oral Cavity" = "#D95F02FF", "Oral Cavity + Oropharynx" = "#E7298AFF", "Unknown" = "#666666FF"),
  CNV = c("-2" = "blue", "-1" = "lightblue", "0" = "white", "1" = "pink","2" = "red"))

# Discrete colour mapping + labels
CNV_colors <- circlize::colorRamp2(
  c(-2, -1, 0, 1, 2),
  c("blue", "lightblue", "white", "pink", "red"))

legend_breaks <- c(-2, -1, 0, 1, 2)
legend_labels <- c("Del (-2)", "Loss (-1)", "Stable (0)", "Gain (+1)", "Amp (+2)")

## SHH ##
SHH_long <- rownames(long_gene_data) %in% SHH
SHH_long <- long_gene_data[SHH_long, ]
SHH_long <- as.matrix(SHH_long)

# Unique CNV values present in the data
present_values <- sort(unique(as.numeric(SHH_long)))

pdf(paste0(output, title, "Copy_Number_Alterations_SHH_Resp.pdf"), width = 10, height = 10)
ComplexHeatmap::pheatmap(
  SHH_long,
  color = CNV_colors,
  cluster_cols = TRUE,
  show_rownames = TRUE,
  show_colnames = FALSE,
  annotation_col = annotations,
  annotation_colors = ann_colors,  
  column_split = as.factor(annotations$Definitive_Response_3_6wk),
  annotation_names_col = FALSE,
  fontsize_row = 12,
  main = paste0(plot_title, " Copy Number Alterations: SHH Biocarta"),
  name = "CNV",
  heatmap_legend_param = list(
    at = c(-2,-1,0,1,2),
    labels = c("Del (-2)","Loss (-1)","Stable (0)","Gain (+1)","Amp (+2)"),
    color_bar = "discrete"))
dev.off()


## EGFR ##
EGFR_long <- rownames(long_gene_data) %in% EGFR
EGFR_long <- long_gene_data[EGFR_long, ]
EGFR_long <- as.matrix(EGFR_long)
EGFR_long <- EGFR_long[EGFR[EGFR %in% rownames(EGFR_long)], ]

# Unique CNV values present in the data
present_values <- sort(unique(as.numeric(EGFR_long)))

pdf(paste0(output, title, "Copy_Number_Alterations_EGFR_Resp.pdf"), width = 10, height = 10)
ComplexHeatmap::pheatmap(
  EGFR_long,
  color = CNV_colors,
  cluster_cols = TRUE,  # Cluster samples
  cluster_rows = FALSE,
  show_rownames = TRUE,
  show_colnames = FALSE,
  annotation_col = annotations,
  annotation_colors = ann_colors,  
  column_split = as.factor(annotations$Definitive_Response_3_6wk),
  annotation_names_col = FALSE,
  fontsize_row = 12,  # Adjust text size
  main = paste0(plot_title, " Copy Number Alterations: EGFR and Ligands"),
  name = "CNV",
  heatmap_legend_param = list(
    at = c(-2,-1,0,1,2),
    labels = c("Del (-2)","Loss (-1)","Stable (0)","Gain (+1)","Amp (+2)"),
    color_bar = "discrete"))
dev.off()

## KRT ##
KRT_long <- rownames(long_gene_data) %in% KRT
KRT_long <- long_gene_data[KRT_long, ]
KRT_long <- as.matrix(KRT_long)

# Get the unique CNV values present in the data
present_values <- sort(unique(as.numeric(KRT_long)))


pdf(paste0(output, title, "Copy_Number_Alterations_KRT_Resp.pdf"), width = 10, height = 10)
ComplexHeatmap::pheatmap(
  KRT_long,
  color = CNV_colors,
  cluster_cols = TRUE,
  show_rownames = TRUE,
  show_colnames = FALSE,
  annotation_col = annotations,
  annotation_colors = ann_colors,  
  column_split = as.factor(annotations$Definitive_Response_3_6wk),
  annotation_names_col = FALSE,
  fontsize_row = 12, 
  main = paste0(plot_title, " Copy Number Alterations: KRT Markers"),
  name = "CNV",
  heatmap_legend_param = list(
    at = c(-2,-1,0,1,2),
    labels = c("Del (-2)","Loss (-1)","Stable (0)","Gain (+1)","Amp (+2)"),
    color_bar = "discrete"))
dev.off()



## RECCURANT CNAs ##
CNA_long <- rownames(long_gene_data) %in% reccurant_cna 
CNA_long <- long_gene_data[CNA_long, ]
CNA_long <- as.matrix(CNA_long)

# Get the unique CNV values present in the data
present_values <- sort(unique(as.numeric(CNA_long)))

pdf(paste0(output, title, "Copy_Number_Alterations_ReccurantCNA_Resp.pdf"), width = 10, height = 10)
ComplexHeatmap::pheatmap(
  CNA_long,
  color = CNV_colors,
  cluster_cols = TRUE,  # Cluster samples
  show_rownames = TRUE,
  show_colnames = FALSE,
  annotation_col = annotations,
  annotation_colors = ann_colors,  
  column_split = as.factor(annotations$Definitive_Response_3_6wk),
  annotation_names_col = FALSE,
  fontsize_row = 12,  # Adjust text size
  main = paste0(plot_title, " Copy Number Alterations: Reccurant CNAs"),
  name = "CNV",
  heatmap_legend_param = list(
    at = c(-2,-1,0,1,2),
    labels = c("Del (-2)","Loss (-1)","Stable (0)","Gain (+1)","Amp (+2)"),
    color_bar = "discrete"))
dev.off()

